
# Constants
# ----------------------------------------------------------------------
%define pkgver 2.1.a2.oga.1
%define pkgname grads-%{pkgver}
%define prefix /opt

# Package Metadata
# ----------------------------------------------------------------------
Summary: Open Grid Analysis and Display System
Name: opengrads
Version: %{pkgver}
Release: 1
License: GPL v2
Group: Application/Science
Source: http://downloads.sourceforge.net/project/opengrads/grads2/%{pkgver}/Linux/%{pkgname}-bundle-x86_64-unknown-linux-gnu.tar.gz
URL: http://opengrads.org/wiki/index.php?title=OpenGrADS_Documentation
Distribution: CentOS 6  # is this correct? n
Vendor: OpenGrADS
Packager: Daniel da Silva <danieldasilva2@acm.org>

%description
The Grid Analysis and Display System (GrADS) is an interactive desktop tool for easy access, manipulation, and visualization of earth science data. The OpenGrADS Project seeks to develop advanced interfaces and extensions based on the main GrADS engine. 


# Targets
# ----------------------------------------------------------------------
%prep
rm -rf $RPM_BUILD_ROOT/%{pkgname}
tar xzvf $RPM_SOURCE_DIR/${pgname}-*.tar.gz

%build


%install
cp -r %{pkgname}/Contents %{prefix}
ln -s %{prefix}/%{pkgname} grads


# File List
# ----------------------------------------------------------------------
%files
%doc 
/opt/grads-2.1.a2.oga.1/gradsdap
/opt/grads-2.1.a2.oga.1/opengrads
/opt/grads-2.1.a2.oga.1/nomads
/opt/grads-2.1.a2.oga.1/gribscan
/opt/grads-2.1.a2.oga.1/lats4d.sh
/opt/grads-2.1.a2.oga.1/Resources
/opt/grads-2.1.a2.oga.1/Resources/Documentation
/opt/grads-2.1.a2.oga.1/Resources/Documentation/advhardcopy.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetshpattr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdenableprint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetrbcols.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetmap.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdgrads.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncsregr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddefine.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncmag.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunctcorr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunctmave.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/commandline.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libipc
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libipc/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libipc/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libipc/libipc.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/lats
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/lats/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/lats/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/lats/liblats.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/gsudf
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/gsudf/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/gsudf/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/gsudf/gsudf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/shape
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/shape/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/shape/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/shape/shape.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/tle
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/tle/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/tle/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/tle/tle.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/path
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/path/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/path/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/path/path.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/grib2
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/grib2/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/grib2/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/grib2/grib2.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/grib2/g2gdf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/saakeskus
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/saakeskus/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/saakeskus/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/saakeskus/saakeskus.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/env
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/env/env.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/env/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/env/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/fish
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/fish/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/fish/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/fish/fish.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libmf
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libmf/libmf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libmf/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libmf/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/orb
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/orb/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/orb/orb.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/orb/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/shfilt
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/shfilt/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/shfilt/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/shfilt/shfilt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/re
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/re/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/re/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/re/re.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libbjt
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libbjt/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libbjt/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/udxt/libbjt/libbjt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/opengrads
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/opengrads/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/opengrads/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/opengrads/opengrads.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/merra
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/merra/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/merra/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/merra/merra.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/grads
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/grads/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/grads/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/bundle/grads/grads.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/sample.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_textw.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_intro.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_main.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_window.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_ncep.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_filew.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_further.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_ex4.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/DAOlogo8.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_simple.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_varw.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/ex3.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_sample.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_ex2.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/ex1.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_intro.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_strw.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/melrose.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/sample2.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_further.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/ex4.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/ncep.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_ex1.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_filem.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_cmdw.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_printm.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_sample.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_ex3.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_dimm.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_run.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_simple.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/ex2.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_run.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gui_optm.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_ref.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/window.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gradball.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/gagui_ref.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/daocd001.gui
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/gagui/DAOlogo8-orig.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/scripts
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/scripts/lats4d
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/scripts/lats4d/index.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/scripts/lats4d/index.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/doc/scripts/lats4d/lats4d.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/footer.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/opengrads.css
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/header.php
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/opengrads.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/og_HEADERlogo.svg
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/og_WIKIlogo.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/ollie.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/opengrads.svg
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/sflogo.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/og_WIKIlogo.svg
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/og_HEADERlogo.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/opengrads/images/ollie.svg
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdexec.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/edemo2.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdshell.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/descriptorfile.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcstyle.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetmissconn.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdreinit.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/reference.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddisablefwrite.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetlooping.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/edemo1.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/expressions.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/ncgen.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/ensembles.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/pdsi.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetmproj.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdropmenu.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetgeotiff.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/font.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetline.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetimprun.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/pagecontrol.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncskip.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/ascii.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/sample_w.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetylab.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/wrfvars.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetchunksize.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetstrsiz.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/fontcontrol.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/users.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsdfopen.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdrun.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/SDFdescriptorfile.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetccols.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqshp.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxyzte.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetblack.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncaave.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig3.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsethempref.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetpoli.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunccoll2gr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/clab_masked.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdswap.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetparea.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetmpdraw.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/display.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/clab_default.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncmaskout.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetloopdim.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdundefine.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdquery.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqdialog.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetkml.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/imageoutput.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/graphics.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddisplay.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/library.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdflush.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunctloop.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawshp.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetccolor.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunclog10.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/shapefiles.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxsize.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig2.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/offtv_diag.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunccdiff.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/sample_temp.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqsdfwrite.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqshades.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncaminlocy.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/sample.grib
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig6.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsethershey.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig4.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunceloop.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetundef.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/grib2.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetgrid.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawxlab.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig1.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetrband.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/scatterplot.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetclskip.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilgxtran.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawylab.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunclog.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/key.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilncdump.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilstnmap.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdquit.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/variableformats.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcthick.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetlatlonlevtime.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdisplay.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcmark.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncoacres.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/map.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/animation.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqshpopts.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetbargap.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxyzt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/edemo6.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/indexlist.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig5.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/wrfgrid.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetlfcols.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/bufr.sample.headers
/opt/grads-2.1.a2.oga.1/Resources/Documentation/xdfsample1.txt
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncaminlocx.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxlabs.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetwxopt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/script.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetyflip.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawbutton.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/reference_card.pdf
/opt/grads-2.1.a2.oga.1/Resources/Documentation/usingstationdata.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsdfwrite.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncsum.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdoutxwd.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/edemo7.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdhelp.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/edemo3.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/sample.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig9.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/functions.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/16colors.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncstnmin.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdredrawbutton.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/advdisplay.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdfile.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetarrlab.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/templates.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqattr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetvrange2.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdstat.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncsin.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetbaropts.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdclear.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetstid.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawpolyf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdopen.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/mathfunctions.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncasin.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetlatlonlevtimeens.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/start.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunctvrh2q.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdwi.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/offt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncgr2stn.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcoslat.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/offtv_1D.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunchcurl.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcachesf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetmdlopts.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/shp_demo2.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/footnote1.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/aboutstationdata.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/xsections.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetgxout.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetgrads.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxaxis.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/reinitialization.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdialog.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/basemap.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/coordinate.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilbufrscan.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqfwrite.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncminloc.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/bufr.sample.data
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetgridln.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdigsize.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdtserbarb.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncmean.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetantialias.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/sample_sfc.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetclopts.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetyaxis.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncoabin.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/graphelem.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetrbrange.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncvint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetylint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqpos.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/reference_card_scl.pdf
/opt/grads-2.1.a2.oga.1/Resources/Documentation/edemo5.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/shp_demo1.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/preprojectedgrids.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawline.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/dimenv.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdcollect.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetmpvals.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawstring.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawmark.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcmax.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetbarbase.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/offt_diag.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetlwid.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetstring.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/pages.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetylevs.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetclip.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdgxprint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/functionsatt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/commands.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/utilities.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetclevs.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdscreen.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetstnprint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsettimelab.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/compression.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetlats.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetshp.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxlevs.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/shp_demo4.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/basemapUS.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_3.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig3.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_6.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/letters.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/basemap_demo2.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig2.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig6.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig4.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_11.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig1.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/key.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_2.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_clear.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig5.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/logom2.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_9.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/pattern_demo2.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_12.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_w.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_b.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/strpos.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/basemap_demo.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_14.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/pattern_demo.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_5.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_7.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_10.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig9.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_4.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/cmarks.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig7.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/tutorial_fig8.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_8.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_13.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/images/dot_15.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetlog1d.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdtserwx.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetfgvals.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetsdfattr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncsmth9.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqdbf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/sample.ncdump
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcsmooth.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdxdfopen.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsettile.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/GrADS.css
/opt/grads-2.1.a2.oga.1/Resources/Documentation/Tutorial_Espanol.doc
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetarrscl.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/edemo4.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilgrib2scan.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdddrawline.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/shp_demo3.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunccos.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawtitle.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncexp.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetmpt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncpow.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetfwrite.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxlpos.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncscorr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawrec.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetylopts.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunchdivg.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/indexalpha.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetclab.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetfont.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncamax.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncstnmax.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawmap.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqfile.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncave.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawwxsym.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawrecf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/xdfsample2.txt
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetvrange.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/bufrdescriptorfile.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncamaxlocx.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/drawingtips.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/grib_levels.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetmpdset.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncmaxloc.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunclterp.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncmin.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncacos.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/basic.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdatawarn.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdreset.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetvpage.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilncgen.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/grib.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunctan.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gadoc.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdmodify.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/stnmap.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/ncdump.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/sample_uv.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetprnopts.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetrgb.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/variable.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetarrowhead.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdefval.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetbutton.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetbackground.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdqens.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxflip.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncatan2.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdclose.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdprintim.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddisableprint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncasum.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetstat.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gsf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig9.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcmin.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/aboutgriddeddata.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxlint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/about.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilgxeps.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetframe.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncsqrt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncsumg.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunctvrh2t.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncgint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncamaxlocy.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetzlog.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncstnave.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gfsens.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig7.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilgribscan.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncabs.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncamean.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/pdef.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetcterp.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxyrev.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncamin.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetwarn.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomddrawdropmenu.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetshpopts.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncconst.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfunctregr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilgxps.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncatot.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetstrmden.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetannot.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetwxcols.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/udf.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/commandsatt.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsettlsupp.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetylabs.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/tutorial_fig8.gif
/opt/grads-2.1.a2.oga.1/Resources/Documentation/supplibs.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncmax.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncasumg.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxlab.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/bufrformat.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/colorcontrol.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdprint.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetxlopts.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/grib_parameters.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetylpos.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetsdfwrite.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdignum.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gfs.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/offt_1D_t1.png
/opt/grads-2.1.a2.oga.1/Resources/Documentation/sample_tau.ctl
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetloopincr.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncfndlvl.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradcomdsetdbuff.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradutilgribmap.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gadocindex.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/gradfuncs2g1d.html
/opt/grads-2.1.a2.oga.1/Resources/Documentation/wrf.ncdump
/opt/grads-2.1.a2.oga.1/Resources/Scripts
/opt/grads-2.1.a2.oga.1/Resources/Scripts/unzoom.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/sample.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/merra_monthly3d.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/utFish.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/merra.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/match.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/cbarc.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/meteogram_eta.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/zoomin.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/ttindex.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/use.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/meteogram_avn.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/panels_demo.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/makebg.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/font.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/string.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/map.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/chdir.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/mconv.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/traj.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/geos.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/yzcomp.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/barcomp.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/merra_monthly2d.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/wi.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/fexists.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/printenv.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/nocmark.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/meteogram_v1.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/defval_demo.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/exists.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/stack.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/cbar_l.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/meteogram_v2.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/basemap.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/rgbmap256.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/sstmask.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/meteogram.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/ex3.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/merra_diurnal2d.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/glob.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/geos5.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/zinterp.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/dewpt.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/isen.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/tlcl.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/xylabel.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/thetae.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/script_math_demo.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/meteogram_v3.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/power.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/cbarn.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/ex1.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/abspath.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/cbar.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/getenv.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/dropmenus.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/tsindex.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/merra_hourly.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/hist.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/dexists.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/melrose.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/zoomprep.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/merra_diurnal3d.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/sample2.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/meteogram_gfs.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/openf.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/ex4.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/ncep.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/wxpanels.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/subplot.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/sweat_index.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/xanim.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/cmapdoc
/opt/grads-2.1.a2.oga.1/Resources/Scripts/cbar_line.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/getatime.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/getctime.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/regrid2.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/isdir.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/meteogram_gfsb.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/getmtime.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/xycomp.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/shear.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/plcl.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/default.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/srh1km.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/dirname.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/connect_the_dots.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/plotskew.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/pinterp.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/rgbmap.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/wxsym.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/unzoomc.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/basename.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/mr_workshop.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/fprintf.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/reimg.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/sed.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/lats4d.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/srh3km.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/zoom.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/ex2.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/cbar_line2.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/isfile.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/merra_3hourly.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/wchill.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/xydiff.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/wordexp.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/zoomout.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/windrose.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/make_ctl.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/setenv.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/window.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/merra_6hourly.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/panels.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/define_colors.gs
/opt/grads-2.1.a2.oga.1/Resources/Scripts/epi.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/nomads.gui
/opt/grads-2.1.a2.oga.1/Resources/Scripts/ept.gsf
/opt/grads-2.1.a2.oga.1/Resources/Scripts/cmap.gs
/opt/grads-2.1.a2.oga.1/Resources/SupportData
/opt/grads-2.1.a2.oga.1/Resources/SupportData/quikscat_2008.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/terra_2008.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/quikscat.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/admin98.shx
/opt/grads-2.1.a2.oga.1/Resources/SupportData/admin98.shp
/opt/grads-2.1.a2.oga.1/Resources/SupportData/mres
/opt/grads-2.1.a2.oga.1/Resources/SupportData/font0.dat
/opt/grads-2.1.a2.oga.1/Resources/SupportData/terra.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/lowres
/opt/grads-2.1.a2.oga.1/Resources/SupportData/aqua.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/font4.dat
/opt/grads-2.1.a2.oga.1/Resources/SupportData/udunits.dat
/opt/grads-2.1.a2.oga.1/Resources/SupportData/font1.dat
/opt/grads-2.1.a2.oga.1/Resources/SupportData/aura.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/terra_2005.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/quikscat_2000.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/terra_2002.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-000-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-058-000-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-010-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-128-001-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-006-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-058-000-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-002-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-008-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-098-001-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-007-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-007-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-007-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-006-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-003-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-128-001-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-006-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-004-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-160000-000001-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-003-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-058-001-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-160000-000001-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-160000-000001-D-forHDGOES
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-005-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/convert.c
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-005-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-160000-006001-B.txt
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-003-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-160000-006001-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-005-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-010-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-009-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-009-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-000-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-000-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-008-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-058000-005000-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-000-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-058-005-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-003-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-010-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-002-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-098-001-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-008-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-058-003-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-058-000-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-160000-006001-D.txt
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-004-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-128-001-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-004-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-128-001-B.001
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-010-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-002-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-005-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-007-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-058-001-D.001
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-009-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-003-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-058-001-B.001
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-160000-000001-B-forHDGOES
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-006-0
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-004-A
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-058-000-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-005-B.new
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-128-001-D.001
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-160000-006001-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2L-058-001-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3L-200-001-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B2M-000-002-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-008-D
/opt/grads-2.1.a2.oga.1/Resources/SupportData/tables/B3M-000-009-B
/opt/grads-2.1.a2.oga.1/Resources/SupportData/font3.dat
/opt/grads-2.1.a2.oga.1/Resources/SupportData/cloudsat.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/quikscat_2005a.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/admin98.dbf
/opt/grads-2.1.a2.oga.1/Resources/SupportData/font2.dat
/opt/grads-2.1.a2.oga.1/Resources/SupportData/calipso.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/hires
/opt/grads-2.1.a2.oga.1/Resources/SupportData/quikscat_2005.tle
/opt/grads-2.1.a2.oga.1/Resources/SupportData/font5.dat
/opt/grads-2.1.a2.oga.1/Resources/SampleDatasets
/opt/grads-2.1.a2.oga.1/Resources/SampleDatasets/model.ctl
/opt/grads-2.1.a2.oga.1/Resources/SampleDatasets/model.gmp
/opt/grads-2.1.a2.oga.1/Resources/SampleDatasets/model.grb
/opt/grads-2.1.a2.oga.1/Resources/Icons
/opt/grads-2.1.a2.oga.1/grib2scan
/opt/grads-2.1.a2.oga.1/Documentation.html
/opt/grads-2.1.a2.oga.1/merra
/opt/grads-2.1.a2.oga.1/bufrscan
/opt/grads-2.1.a2.oga.1/stnmap
/opt/grads-2.1.a2.oga.1/sgrads
/opt/grads-2.1.a2.oga.1/wgrib
/opt/grads-2.1.a2.oga.1/Linux
/opt/grads-2.1.a2.oga.1/Linux/x86_64@
/opt/grads-2.1.a2.oga.1/Linux/Versions
/opt/grads-2.1.a2.oga.1/Linux/Versions/Current@
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/fish.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/VERSION
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libbjt.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libmf.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/re.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/shfilt.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gribscan
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/grib2scan
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gsudf.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/bufrscan
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/stnmap
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/sgrads
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/wgrib
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/orb.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/liblats.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/saakeskus.pod_
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/tle.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXaw.so.7
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libICE.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libc.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXmu.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXpm.so.4
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libuuid.so.1
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libpthread.so.0
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libm.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libX11.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libgcc_s.so.1
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXt.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXau.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/librt.so.1
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libxcb.so.1
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXext.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libSM.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libdl.so.2
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libstdc++.so.6
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/grads
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gribmap
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/libipc.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/fish.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/re.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/gsf.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/gsudf.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libbjt.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/bjt.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/liblats.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/re.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libhello.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/hello.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/ams.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/path.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/orb.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/orb.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/shfilt.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libipc.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/tle.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/shfilt.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libmf.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libgfortran.so.3
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/ipc.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/env.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/fish.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/lats.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/tle.udxt
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libmf.gex
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/path.pod
/opt/grads-2.1.a2.oga.1/Linux/Versions/2.1.a2.oga.1/x86_64/env.pod
/opt/grads-2.1.a2.oga.1/grads
/opt/grads-2.1.a2.oga.1/geos5
/opt/grads-2.1.a2.oga.1/gribmap




