
# Constants
# ----------------------------------------------------------------------
%define pkgver 2.1.a2.oga.1
%define pkgname grads-%{pkgver}
%define prefix /home/dedasilv/tmp/fake_opt

# Package Metadata
# ----------------------------------------------------------------------
Summary: Open Grid Analysis and Display System
Name: opengrads
Version: %{pkgver}
Release: 1
License: GPL v2
Group: Application/Science
Source: http://downloads.sourceforge.net/project/opengrads/grads2/%{pkgver}/Linux/%{pkgname}-bundle-x86_64-unknown-linux-gnu.tar.gz
URL: http://opengrads.org/wiki/index.php?title=OpenGrADS_Documentation
Distribution: CentOS 6  # is this correct? n
Vendor: OpenGrADS
Packager: Daniel da Silva <danieldasilva2@acm.org>

%description
The Grid Analysis and Display System (GrADS) is an interactive desktop tool for easy access, manipulation, and visualization of earth science data. The OpenGrADS Project seeks to develop advanced interfaces and extensions based on the main GrADS engine. 


# Targets
# ----------------------------------------------------------------------
%prep
rm -rf $RPM_BUILD_ROOT/*
tar xzvf $RPM_SOURCE_DIR/%{pkgname}-bundle-x86_64-unknown-linux-gnu.tar.gz

%build


%install
mkdir -p %{prefix}
cp -r %{pkgname}/Contents %{prefix}/%{pkgname}
rm %{prefix}/grads
ln -s %{prefix}/%{pkgname} %{prefix}/grads

# File List
# ----------------------------------------------------------------------
%files
%doc 
%{prefix}/%{pkgname}/gradsdap
%{prefix}/%{pkgname}/opengrads
%{prefix}/%{pkgname}/nomads
%{prefix}/%{pkgname}/gribscan
%{prefix}/%{pkgname}/lats4d.sh
%{prefix}/%{pkgname}/Resources
%{prefix}/%{pkgname}/Resources/Documentation
%{prefix}/%{pkgname}/Resources/Documentation/advhardcopy.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetshpattr.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdenableprint.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetrbcols.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetmap.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdgrads.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncsregr.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddefine.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncmag.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunctcorr.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunctmave.html
%{prefix}/%{pkgname}/Resources/Documentation/commandline.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libipc
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libipc/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libipc/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libipc/libipc.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/lats
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/lats/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/lats/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/lats/liblats.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/gsudf
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/gsudf/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/gsudf/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/gsudf/gsudf.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/shape
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/shape/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/shape/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/shape/shape.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/tle
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/tle/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/tle/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/tle/tle.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/path
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/path/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/path/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/path/path.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/grib2
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/grib2/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/grib2/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/grib2/grib2.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/grib2/g2gdf.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/saakeskus
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/saakeskus/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/saakeskus/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/saakeskus/saakeskus.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/env
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/env/env.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/env/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/env/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/fish
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/fish/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/fish/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/fish/fish.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libmf
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libmf/libmf.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libmf/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libmf/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/orb
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/orb/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/orb/orb.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/orb/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/shfilt
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/shfilt/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/shfilt/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/shfilt/shfilt.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/re
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/re/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/re/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/re/re.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libbjt
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libbjt/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libbjt/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/udxt/libbjt/libbjt.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/opengrads
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/opengrads/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/opengrads/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/opengrads/opengrads.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/merra
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/merra/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/merra/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/merra/merra.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/grads
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/grads/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/grads/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/bundle/grads/grads.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/sample.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_textw.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_intro.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_main.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_window.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_ncep.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_filew.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_further.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_ex4.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/DAOlogo8.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_simple.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_varw.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/ex3.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_sample.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_ex2.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/ex1.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_intro.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_strw.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/melrose.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/sample2.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_further.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/ex4.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/ncep.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_ex1.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_filem.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_cmdw.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_printm.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_sample.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_ex3.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_dimm.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_run.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_simple.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/ex2.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_run.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gui_optm.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_ref.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/window.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gradball.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/gagui_ref.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/daocd001.gui
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/gagui/DAOlogo8-orig.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/scripts
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/scripts/lats4d
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/scripts/lats4d/index.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/scripts/lats4d/index.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/doc/scripts/lats4d/lats4d.html
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/footer.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/opengrads.css
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/header.php
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/opengrads.png
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/og_HEADERlogo.svg
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/og_WIKIlogo.png
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/ollie.png
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/opengrads.svg
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/sflogo.gif
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/og_WIKIlogo.svg
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/og_HEADERlogo.png
%{prefix}/%{pkgname}/Resources/Documentation/opengrads/images/ollie.svg
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdexec.html
%{prefix}/%{pkgname}/Resources/Documentation/edemo2.png
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdshell.html
%{prefix}/%{pkgname}/Resources/Documentation/descriptorfile.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcstyle.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetmissconn.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdreinit.html
%{prefix}/%{pkgname}/Resources/Documentation/reference.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddisablefwrite.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetlooping.html
%{prefix}/%{pkgname}/Resources/Documentation/edemo1.png
%{prefix}/%{pkgname}/Resources/Documentation/expressions.html
%{prefix}/%{pkgname}/Resources/Documentation/ncgen.html
%{prefix}/%{pkgname}/Resources/Documentation/ensembles.html
%{prefix}/%{pkgname}/Resources/Documentation/pdsi.png
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetmproj.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdropmenu.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetgeotiff.html
%{prefix}/%{pkgname}/Resources/Documentation/font.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetline.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetimprun.html
%{prefix}/%{pkgname}/Resources/Documentation/pagecontrol.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncskip.html
%{prefix}/%{pkgname}/Resources/Documentation/ascii.html
%{prefix}/%{pkgname}/Resources/Documentation/sample_w.ctl
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetylab.html
%{prefix}/%{pkgname}/Resources/Documentation/wrfvars.ctl
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetchunksize.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetstrsiz.html
%{prefix}/%{pkgname}/Resources/Documentation/fontcontrol.html
%{prefix}/%{pkgname}/Resources/Documentation/users.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsdfopen.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdrun.html
%{prefix}/%{pkgname}/Resources/Documentation/SDFdescriptorfile.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetccols.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqshp.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxyzte.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetblack.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncaave.html
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig3.gif
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsethempref.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetpoli.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunccoll2gr.html
%{prefix}/%{pkgname}/Resources/Documentation/clab_masked.png
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdswap.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetparea.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetmpdraw.html
%{prefix}/%{pkgname}/Resources/Documentation/display.html
%{prefix}/%{pkgname}/Resources/Documentation/clab_default.png
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncmaskout.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetloopdim.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdundefine.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdquery.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqdialog.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetkml.html
%{prefix}/%{pkgname}/Resources/Documentation/imageoutput.html
%{prefix}/%{pkgname}/Resources/Documentation/graphics.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddisplay.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcint.html
%{prefix}/%{pkgname}/Resources/Documentation/library.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdflush.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunctloop.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawshp.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetccolor.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunclog10.html
%{prefix}/%{pkgname}/Resources/Documentation/shapefiles.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxsize.html
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig2.gif
%{prefix}/%{pkgname}/Resources/Documentation/offtv_diag.png
%{prefix}/%{pkgname}/Resources/Documentation/gradfunccdiff.html
%{prefix}/%{pkgname}/Resources/Documentation/sample_temp.ctl
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqsdfwrite.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqshades.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncaminlocy.html
%{prefix}/%{pkgname}/Resources/Documentation/sample.grib
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig6.gif
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsethershey.html
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig4.gif
%{prefix}/%{pkgname}/Resources/Documentation/gradfunceloop.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetundef.html
%{prefix}/%{pkgname}/Resources/Documentation/grib2.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetgrid.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawxlab.html
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig1.gif
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetrband.html
%{prefix}/%{pkgname}/Resources/Documentation/scatterplot.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetclskip.html
%{prefix}/%{pkgname}/Resources/Documentation/gradutilgxtran.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawylab.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunclog.html
%{prefix}/%{pkgname}/Resources/Documentation/key.gif
%{prefix}/%{pkgname}/Resources/Documentation/gradutilncdump.html
%{prefix}/%{pkgname}/Resources/Documentation/gradutilstnmap.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdquit.html
%{prefix}/%{pkgname}/Resources/Documentation/variableformats.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcthick.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetlatlonlevtime.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdisplay.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcmark.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncoacres.html
%{prefix}/%{pkgname}/Resources/Documentation/map.html
%{prefix}/%{pkgname}/Resources/Documentation/animation.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqshpopts.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetbargap.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxyzt.html
%{prefix}/%{pkgname}/Resources/Documentation/edemo6.png
%{prefix}/%{pkgname}/Resources/Documentation/indexlist.html
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig5.gif
%{prefix}/%{pkgname}/Resources/Documentation/wrfgrid.ctl
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetlfcols.html
%{prefix}/%{pkgname}/Resources/Documentation/bufr.sample.headers
%{prefix}/%{pkgname}/Resources/Documentation/xdfsample1.txt
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncaminlocx.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxlabs.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetwxopt.html
%{prefix}/%{pkgname}/Resources/Documentation/script.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetyflip.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawbutton.html
%{prefix}/%{pkgname}/Resources/Documentation/reference_card.pdf
%{prefix}/%{pkgname}/Resources/Documentation/usingstationdata.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsdfwrite.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncsum.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdoutxwd.html
%{prefix}/%{pkgname}/Resources/Documentation/edemo7.png
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdhelp.html
%{prefix}/%{pkgname}/Resources/Documentation/edemo3.png
%{prefix}/%{pkgname}/Resources/Documentation/sample.ctl
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig9.png
%{prefix}/%{pkgname}/Resources/Documentation/functions.html
%{prefix}/%{pkgname}/Resources/Documentation/16colors.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncstnmin.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdredrawbutton.html
%{prefix}/%{pkgname}/Resources/Documentation/advdisplay.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdfile.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetarrlab.html
%{prefix}/%{pkgname}/Resources/Documentation/templates.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqattr.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetvrange2.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdstat.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncsin.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetbaropts.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdclear.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetstid.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawpolyf.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdopen.html
%{prefix}/%{pkgname}/Resources/Documentation/mathfunctions.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncasin.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetlatlonlevtimeens.html
%{prefix}/%{pkgname}/Resources/Documentation/start.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunctvrh2q.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdwi.html
%{prefix}/%{pkgname}/Resources/Documentation/offt.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncgr2stn.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcoslat.html
%{prefix}/%{pkgname}/Resources/Documentation/offtv_1D.png
%{prefix}/%{pkgname}/Resources/Documentation/gradfunchcurl.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcachesf.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetmdlopts.html
%{prefix}/%{pkgname}/Resources/Documentation/shp_demo2.png
%{prefix}/%{pkgname}/Resources/Documentation/footnote1.html
%{prefix}/%{pkgname}/Resources/Documentation/aboutstationdata.html
%{prefix}/%{pkgname}/Resources/Documentation/xsections.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetgxout.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetgrads.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxaxis.html
%{prefix}/%{pkgname}/Resources/Documentation/reinitialization.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdialog.html
%{prefix}/%{pkgname}/Resources/Documentation/basemap.html
%{prefix}/%{pkgname}/Resources/Documentation/coordinate.html
%{prefix}/%{pkgname}/Resources/Documentation/gradutilbufrscan.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqfwrite.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncminloc.html
%{prefix}/%{pkgname}/Resources/Documentation/bufr.sample.data
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetgridln.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdigsize.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdtserbarb.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncmean.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetantialias.html
%{prefix}/%{pkgname}/Resources/Documentation/sample_sfc.ctl
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetclopts.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetyaxis.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncoabin.html
%{prefix}/%{pkgname}/Resources/Documentation/graphelem.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetrbrange.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncvint.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetylint.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqpos.html
%{prefix}/%{pkgname}/Resources/Documentation/reference_card_scl.pdf
%{prefix}/%{pkgname}/Resources/Documentation/edemo5.png
%{prefix}/%{pkgname}/Resources/Documentation/shp_demo1.png
%{prefix}/%{pkgname}/Resources/Documentation/preprojectedgrids.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawline.html
%{prefix}/%{pkgname}/Resources/Documentation/dimenv.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdcollect.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetmpvals.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawstring.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawmark.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcmax.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetbarbase.html
%{prefix}/%{pkgname}/Resources/Documentation/offt_diag.png
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetlwid.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetstring.html
%{prefix}/%{pkgname}/Resources/Documentation/pages.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetylevs.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetclip.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdgxprint.html
%{prefix}/%{pkgname}/Resources/Documentation/functionsatt.html
%{prefix}/%{pkgname}/Resources/Documentation/commands.html
%{prefix}/%{pkgname}/Resources/Documentation/utilities.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetclevs.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdscreen.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetstnprint.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsettimelab.html
%{prefix}/%{pkgname}/Resources/Documentation/compression.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetlats.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetshp.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxlevs.html
%{prefix}/%{pkgname}/Resources/Documentation/images
%{prefix}/%{pkgname}/Resources/Documentation/images/shp_demo4.png
%{prefix}/%{pkgname}/Resources/Documentation/images/basemapUS.png
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_3.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig3.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_6.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/letters.png
%{prefix}/%{pkgname}/Resources/Documentation/images/basemap_demo2.png
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig2.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig6.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig4.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_11.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig1.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/key.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_2.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_clear.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig5.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/logom2.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_9.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/pattern_demo2.png
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_12.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_w.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_b.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/strpos.png
%{prefix}/%{pkgname}/Resources/Documentation/images/basemap_demo.png
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_14.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/pattern_demo.png
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_5.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_7.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_10.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig9.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_4.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/cmarks.png
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig7.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/tutorial_fig8.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_8.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_13.gif
%{prefix}/%{pkgname}/Resources/Documentation/images/dot_15.gif
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetlog1d.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdtserwx.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetfgvals.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetsdfattr.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncsmth9.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqdbf.html
%{prefix}/%{pkgname}/Resources/Documentation/sample.ncdump
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcsmooth.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdxdfopen.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsettile.html
%{prefix}/%{pkgname}/Resources/Documentation/GrADS.css
%{prefix}/%{pkgname}/Resources/Documentation/Tutorial_Espanol.doc
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetarrscl.html
%{prefix}/%{pkgname}/Resources/Documentation/edemo4.png
%{prefix}/%{pkgname}/Resources/Documentation/gradutilgrib2scan.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdddrawline.html
%{prefix}/%{pkgname}/Resources/Documentation/shp_demo3.png
%{prefix}/%{pkgname}/Resources/Documentation/gradfunccos.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawtitle.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncexp.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetmpt.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncpow.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetfwrite.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxlpos.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncscorr.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawrec.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetylopts.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunchdivg.html
%{prefix}/%{pkgname}/Resources/Documentation/indexalpha.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetclab.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetfont.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncamax.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncstnmax.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawmap.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqfile.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncave.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawwxsym.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawrecf.html
%{prefix}/%{pkgname}/Resources/Documentation/xdfsample2.txt
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetvrange.html
%{prefix}/%{pkgname}/Resources/Documentation/bufrdescriptorfile.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncamaxlocx.html
%{prefix}/%{pkgname}/Resources/Documentation/drawingtips.html
%{prefix}/%{pkgname}/Resources/Documentation/grib_levels.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetmpdset.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncmaxloc.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunclterp.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncmin.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncacos.html
%{prefix}/%{pkgname}/Resources/Documentation/basic.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdatawarn.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdreset.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetvpage.html
%{prefix}/%{pkgname}/Resources/Documentation/gradutilncgen.html
%{prefix}/%{pkgname}/Resources/Documentation/grib.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunctan.html
%{prefix}/%{pkgname}/Resources/Documentation/gadoc.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdmodify.html
%{prefix}/%{pkgname}/Resources/Documentation/stnmap.html
%{prefix}/%{pkgname}/Resources/Documentation/ncdump.html
%{prefix}/%{pkgname}/Resources/Documentation/sample_uv.ctl
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetprnopts.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetrgb.html
%{prefix}/%{pkgname}/Resources/Documentation/variable.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetarrowhead.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdefval.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetbutton.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetbackground.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdqens.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxflip.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncatan2.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdclose.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdprintim.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddisableprint.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncasum.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetstat.html
%{prefix}/%{pkgname}/Resources/Documentation/gsf.html
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig9.gif
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcmin.html
%{prefix}/%{pkgname}/Resources/Documentation/aboutgriddeddata.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxlint.html
%{prefix}/%{pkgname}/Resources/Documentation/about.html
%{prefix}/%{pkgname}/Resources/Documentation/gradutilgxeps.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetframe.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncsqrt.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncsumg.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunctvrh2t.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncgint.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncamaxlocy.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetzlog.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncstnave.html
%{prefix}/%{pkgname}/Resources/Documentation/gfsens.ctl
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig7.gif
%{prefix}/%{pkgname}/Resources/Documentation/tutorial.html
%{prefix}/%{pkgname}/Resources/Documentation/gradutilgribscan.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncabs.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncamean.html
%{prefix}/%{pkgname}/Resources/Documentation/pdef.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetcterp.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxyrev.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncamin.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetwarn.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomddrawdropmenu.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetshpopts.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncconst.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfunctregr.html
%{prefix}/%{pkgname}/Resources/Documentation/gradutilgxps.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncatot.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetstrmden.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetannot.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetwxcols.html
%{prefix}/%{pkgname}/Resources/Documentation/udf.html
%{prefix}/%{pkgname}/Resources/Documentation/commandsatt.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsettlsupp.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetylabs.html
%{prefix}/%{pkgname}/Resources/Documentation/tutorial_fig8.gif
%{prefix}/%{pkgname}/Resources/Documentation/supplibs.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncmax.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncasumg.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxlab.html
%{prefix}/%{pkgname}/Resources/Documentation/bufrformat.html
%{prefix}/%{pkgname}/Resources/Documentation/colorcontrol.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdprint.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetxlopts.html
%{prefix}/%{pkgname}/Resources/Documentation/grib_parameters.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetylpos.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetsdfwrite.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdignum.html
%{prefix}/%{pkgname}/Resources/Documentation/gfs.ctl
%{prefix}/%{pkgname}/Resources/Documentation/offt_1D_t1.png
%{prefix}/%{pkgname}/Resources/Documentation/sample_tau.ctl
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetloopincr.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncfndlvl.html
%{prefix}/%{pkgname}/Resources/Documentation/gradcomdsetdbuff.html
%{prefix}/%{pkgname}/Resources/Documentation/gradutilgribmap.html
%{prefix}/%{pkgname}/Resources/Documentation/gadocindex.html
%{prefix}/%{pkgname}/Resources/Documentation/gradfuncs2g1d.html
%{prefix}/%{pkgname}/Resources/Documentation/wrf.ncdump
%{prefix}/%{pkgname}/Resources/Scripts
%{prefix}/%{pkgname}/Resources/Scripts/unzoom.gs
%{prefix}/%{pkgname}/Resources/Scripts/sample.gui
%{prefix}/%{pkgname}/Resources/Scripts/merra_monthly3d.gs
%{prefix}/%{pkgname}/Resources/Scripts/utFish.gs
%{prefix}/%{pkgname}/Resources/Scripts/merra.gui
%{prefix}/%{pkgname}/Resources/Scripts/match.gsf
%{prefix}/%{pkgname}/Resources/Scripts/cbarc.gs
%{prefix}/%{pkgname}/Resources/Scripts/meteogram_eta.gs
%{prefix}/%{pkgname}/Resources/Scripts/zoomin.gs
%{prefix}/%{pkgname}/Resources/Scripts/ttindex.gsf
%{prefix}/%{pkgname}/Resources/Scripts/use.gs
%{prefix}/%{pkgname}/Resources/Scripts/meteogram_avn.gs
%{prefix}/%{pkgname}/Resources/Scripts/panels_demo.gs
%{prefix}/%{pkgname}/Resources/Scripts/makebg.gs
%{prefix}/%{pkgname}/Resources/Scripts/font.gs
%{prefix}/%{pkgname}/Resources/Scripts/string.gs
%{prefix}/%{pkgname}/Resources/Scripts/map.gs
%{prefix}/%{pkgname}/Resources/Scripts/chdir.gsf
%{prefix}/%{pkgname}/Resources/Scripts/mconv.gs
%{prefix}/%{pkgname}/Resources/Scripts/traj.gs
%{prefix}/%{pkgname}/Resources/Scripts/geos.gsf
%{prefix}/%{pkgname}/Resources/Scripts/yzcomp.gs
%{prefix}/%{pkgname}/Resources/Scripts/barcomp.gs
%{prefix}/%{pkgname}/Resources/Scripts/merra_monthly2d.gs
%{prefix}/%{pkgname}/Resources/Scripts/wi.gs
%{prefix}/%{pkgname}/Resources/Scripts/fexists.gsf
%{prefix}/%{pkgname}/Resources/Scripts/printenv.gsf
%{prefix}/%{pkgname}/Resources/Scripts/nocmark.gs
%{prefix}/%{pkgname}/Resources/Scripts/meteogram_v1.gs
%{prefix}/%{pkgname}/Resources/Scripts/defval_demo.gs
%{prefix}/%{pkgname}/Resources/Scripts/exists.gsf
%{prefix}/%{pkgname}/Resources/Scripts/stack.gs
%{prefix}/%{pkgname}/Resources/Scripts/cbar_l.gs
%{prefix}/%{pkgname}/Resources/Scripts/meteogram_v2.gs
%{prefix}/%{pkgname}/Resources/Scripts/basemap.gs
%{prefix}/%{pkgname}/Resources/Scripts/rgbmap256.gs
%{prefix}/%{pkgname}/Resources/Scripts/sstmask.gs
%{prefix}/%{pkgname}/Resources/Scripts/meteogram.gs
%{prefix}/%{pkgname}/Resources/Scripts/ex3.gui
%{prefix}/%{pkgname}/Resources/Scripts/merra_diurnal2d.gs
%{prefix}/%{pkgname}/Resources/Scripts/glob.gsf
%{prefix}/%{pkgname}/Resources/Scripts/geos5.gui
%{prefix}/%{pkgname}/Resources/Scripts/zinterp.gs
%{prefix}/%{pkgname}/Resources/Scripts/dewpt.gsf
%{prefix}/%{pkgname}/Resources/Scripts/isen.gs
%{prefix}/%{pkgname}/Resources/Scripts/tlcl.gsf
%{prefix}/%{pkgname}/Resources/Scripts/xylabel.gs
%{prefix}/%{pkgname}/Resources/Scripts/thetae.gs
%{prefix}/%{pkgname}/Resources/Scripts/script_math_demo.gs
%{prefix}/%{pkgname}/Resources/Scripts/meteogram_v3.gs
%{prefix}/%{pkgname}/Resources/Scripts/power.gs
%{prefix}/%{pkgname}/Resources/Scripts/cbarn.gs
%{prefix}/%{pkgname}/Resources/Scripts/ex1.gui
%{prefix}/%{pkgname}/Resources/Scripts/abspath.gsf
%{prefix}/%{pkgname}/Resources/Scripts/cbar.gs
%{prefix}/%{pkgname}/Resources/Scripts/getenv.gsf
%{prefix}/%{pkgname}/Resources/Scripts/dropmenus.gs
%{prefix}/%{pkgname}/Resources/Scripts/tsindex.gsf
%{prefix}/%{pkgname}/Resources/Scripts/merra_hourly.gs
%{prefix}/%{pkgname}/Resources/Scripts/hist.gs
%{prefix}/%{pkgname}/Resources/Scripts/dexists.gsf
%{prefix}/%{pkgname}/Resources/Scripts/melrose.gui
%{prefix}/%{pkgname}/Resources/Scripts/zoomprep.gs
%{prefix}/%{pkgname}/Resources/Scripts/merra_diurnal3d.gs
%{prefix}/%{pkgname}/Resources/Scripts/sample2.gui
%{prefix}/%{pkgname}/Resources/Scripts/meteogram_gfs.gs
%{prefix}/%{pkgname}/Resources/Scripts/openf.gs
%{prefix}/%{pkgname}/Resources/Scripts/ex4.gui
%{prefix}/%{pkgname}/Resources/Scripts/ncep.gui
%{prefix}/%{pkgname}/Resources/Scripts/wxpanels.gs
%{prefix}/%{pkgname}/Resources/Scripts/subplot.gs
%{prefix}/%{pkgname}/Resources/Scripts/sweat_index.gs
%{prefix}/%{pkgname}/Resources/Scripts/xanim.gs
%{prefix}/%{pkgname}/Resources/Scripts/cmapdoc
%{prefix}/%{pkgname}/Resources/Scripts/cbar_line.gs
%{prefix}/%{pkgname}/Resources/Scripts/getatime.gsf
%{prefix}/%{pkgname}/Resources/Scripts/getctime.gsf
%{prefix}/%{pkgname}/Resources/Scripts/regrid2.gsf
%{prefix}/%{pkgname}/Resources/Scripts/isdir.gsf
%{prefix}/%{pkgname}/Resources/Scripts/meteogram_gfsb.gs
%{prefix}/%{pkgname}/Resources/Scripts/getmtime.gsf
%{prefix}/%{pkgname}/Resources/Scripts/xycomp.gs
%{prefix}/%{pkgname}/Resources/Scripts/shear.gsf
%{prefix}/%{pkgname}/Resources/Scripts/plcl.gsf
%{prefix}/%{pkgname}/Resources/Scripts/default.gui
%{prefix}/%{pkgname}/Resources/Scripts/srh1km.gsf
%{prefix}/%{pkgname}/Resources/Scripts/dirname.gsf
%{prefix}/%{pkgname}/Resources/Scripts/connect_the_dots.gs
%{prefix}/%{pkgname}/Resources/Scripts/plotskew.gs
%{prefix}/%{pkgname}/Resources/Scripts/pinterp.gs
%{prefix}/%{pkgname}/Resources/Scripts/rgbmap.gs
%{prefix}/%{pkgname}/Resources/Scripts/wxsym.gs
%{prefix}/%{pkgname}/Resources/Scripts/unzoomc.gs
%{prefix}/%{pkgname}/Resources/Scripts/basename.gsf
%{prefix}/%{pkgname}/Resources/Scripts/mr_workshop.gui
%{prefix}/%{pkgname}/Resources/Scripts/fprintf.gs
%{prefix}/%{pkgname}/Resources/Scripts/reimg.gsf
%{prefix}/%{pkgname}/Resources/Scripts/sed.gsf
%{prefix}/%{pkgname}/Resources/Scripts/lats4d.gs
%{prefix}/%{pkgname}/Resources/Scripts/srh3km.gsf
%{prefix}/%{pkgname}/Resources/Scripts/zoom.gs
%{prefix}/%{pkgname}/Resources/Scripts/ex2.gui
%{prefix}/%{pkgname}/Resources/Scripts/cbar_line2.gs
%{prefix}/%{pkgname}/Resources/Scripts/isfile.gsf
%{prefix}/%{pkgname}/Resources/Scripts/merra_3hourly.gs
%{prefix}/%{pkgname}/Resources/Scripts/wchill.gsf
%{prefix}/%{pkgname}/Resources/Scripts/xydiff.gs
%{prefix}/%{pkgname}/Resources/Scripts/wordexp.gsf
%{prefix}/%{pkgname}/Resources/Scripts/zoomout.gs
%{prefix}/%{pkgname}/Resources/Scripts/windrose.gs
%{prefix}/%{pkgname}/Resources/Scripts/make_ctl.gs
%{prefix}/%{pkgname}/Resources/Scripts/setenv.gsf
%{prefix}/%{pkgname}/Resources/Scripts/window.gui
%{prefix}/%{pkgname}/Resources/Scripts/merra_6hourly.gs
%{prefix}/%{pkgname}/Resources/Scripts/panels.gsf
%{prefix}/%{pkgname}/Resources/Scripts/define_colors.gs
%{prefix}/%{pkgname}/Resources/Scripts/epi.gsf
%{prefix}/%{pkgname}/Resources/Scripts/nomads.gui
%{prefix}/%{pkgname}/Resources/Scripts/ept.gsf
%{prefix}/%{pkgname}/Resources/Scripts/cmap.gs
%{prefix}/%{pkgname}/Resources/SupportData
%{prefix}/%{pkgname}/Resources/SupportData/quikscat_2008.tle
%{prefix}/%{pkgname}/Resources/SupportData/terra_2008.tle
%{prefix}/%{pkgname}/Resources/SupportData/quikscat.tle
%{prefix}/%{pkgname}/Resources/SupportData/admin98.shx
%{prefix}/%{pkgname}/Resources/SupportData/admin98.shp
%{prefix}/%{pkgname}/Resources/SupportData/mres
%{prefix}/%{pkgname}/Resources/SupportData/font0.dat
%{prefix}/%{pkgname}/Resources/SupportData/terra.tle
%{prefix}/%{pkgname}/Resources/SupportData/lowres
%{prefix}/%{pkgname}/Resources/SupportData/aqua.tle
%{prefix}/%{pkgname}/Resources/SupportData/font4.dat
%{prefix}/%{pkgname}/Resources/SupportData/udunits.dat
%{prefix}/%{pkgname}/Resources/SupportData/font1.dat
%{prefix}/%{pkgname}/Resources/SupportData/aura.tle
%{prefix}/%{pkgname}/Resources/SupportData/terra_2005.tle
%{prefix}/%{pkgname}/Resources/SupportData/quikscat_2000.tle
%{prefix}/%{pkgname}/Resources/SupportData/terra_2002.tle
%{prefix}/%{pkgname}/Resources/SupportData/tables
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-000-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-058-000-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-010-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-128-001-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-006-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-058-000-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-002-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-008-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-098-001-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-007-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-007-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-007-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-006-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-003-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-128-001-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-006-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-004-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-160000-000001-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-003-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-058-001-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-160000-000001-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-160000-000001-D-forHDGOES
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-005-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/convert.c
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-005-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-160000-006001-B.txt
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-003-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-160000-006001-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-005-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-010-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-009-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-009-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-000-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-000-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-008-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-058000-005000-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-000-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-058-005-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-003-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-010-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-002-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-098-001-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-008-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-058-003-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-058-000-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-160000-006001-D.txt
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-004-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-128-001-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-004-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-128-001-B.001
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-010-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-002-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-005-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-007-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-058-001-D.001
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-009-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-003-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-058-001-B.001
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-160000-000001-B-forHDGOES
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-006-0
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-004-A
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-058-000-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-005-B.new
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-128-001-D.001
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-160000-006001-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2L-058-001-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3L-200-001-B
%{prefix}/%{pkgname}/Resources/SupportData/tables/B2M-000-002-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-008-D
%{prefix}/%{pkgname}/Resources/SupportData/tables/B3M-000-009-B
%{prefix}/%{pkgname}/Resources/SupportData/font3.dat
%{prefix}/%{pkgname}/Resources/SupportData/cloudsat.tle
%{prefix}/%{pkgname}/Resources/SupportData/quikscat_2005a.tle
%{prefix}/%{pkgname}/Resources/SupportData/admin98.dbf
%{prefix}/%{pkgname}/Resources/SupportData/font2.dat
%{prefix}/%{pkgname}/Resources/SupportData/calipso.tle
%{prefix}/%{pkgname}/Resources/SupportData/hires
%{prefix}/%{pkgname}/Resources/SupportData/quikscat_2005.tle
%{prefix}/%{pkgname}/Resources/SupportData/font5.dat
%{prefix}/%{pkgname}/Resources/SampleDatasets
%{prefix}/%{pkgname}/Resources/SampleDatasets/model.ctl
%{prefix}/%{pkgname}/Resources/SampleDatasets/model.gmp
%{prefix}/%{pkgname}/Resources/SampleDatasets/model.grb
%{prefix}/%{pkgname}/Resources/Icons
%{prefix}/%{pkgname}/grib2scan
%{prefix}/%{pkgname}/Documentation.html
%{prefix}/%{pkgname}/merra
%{prefix}/%{pkgname}/bufrscan
%{prefix}/%{pkgname}/stnmap
%{prefix}/%{pkgname}/sgrads
%{prefix}/%{pkgname}/wgrib
%{prefix}/%{pkgname}/Linux
%{prefix}/%{pkgname}/Linux/x86_64@
%{prefix}/%{pkgname}/Linux/Versions
%{prefix}/%{pkgname}/Linux/Versions/Current@
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/fish.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/VERSION
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libbjt.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libmf.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/re.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/shfilt.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gribscan
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/grib2scan
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gsudf.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/bufrscan
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/stnmap
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/sgrads
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/wgrib
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/orb.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/liblats.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/saakeskus.pod_
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/tle.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXaw.so.7
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libICE.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libc.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXmu.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXpm.so.4
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libuuid.so.1
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libpthread.so.0
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libm.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libX11.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libgcc_s.so.1
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXt.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXau.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/librt.so.1
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libxcb.so.1
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libXext.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libSM.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libdl.so.2
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libs/libstdc++.so.6
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/grads
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gribmap
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/libipc.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/fish.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/re.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/gsf.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/gsudf.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libbjt.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/bjt.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/liblats.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/re.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libhello.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/hello.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/ams.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/path.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/orb.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/orb.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/shfilt.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libipc.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/tle.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/shfilt.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libmf.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libgfortran.so.3
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/ipc.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/env.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/fish.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/lats.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/tle.udxt
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/gex/libmf.gex
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/path.pod
%{prefix}/%{pkgname}/Linux/Versions/2.1.a2.oga.1/x86_64/env.pod
%{prefix}/%{pkgname}/grads
%{prefix}/%{pkgname}/geos5
%{prefix}/%{pkgname}/gribmap




